[build]
  command = "npm install && npm run build"
  # functions = "functions"
  # functions="express"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
