
# limitation of the functions
# it looks like react-app/build does need to be
# tracked in the git repo?
[build]
  command = "npm install && npm run build"
  # functions = "functions"
  # functions="express"

#https://docs.netlify.com/build/functions/optional-configuration/?data-tab=TypeScript
#https://www.netlify.com/blog/2021/08/12/how-to-include-files-in-netlify-serverless-functions/
[functions]
# I don't really understand why but sqlite3 needs to be listed
# as an external_node_modules here.
# Most other dependencies can just be included in
# package.json as normal
  external_node_modules = ["express", "sqlite3"]
  node_bundler = "esbuild"
# netlify functions are on demand / serverless
# so any files need to be listed if included
# include sqlite and the react build.
  included_files = ["database.sqlite", "react-app/build/**"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

#https://docs.netlify.com/manage/routing/redirects/redirect-options/#splats
[[redirects]]
  force = false
  from = "/*"
  status = 200
  to = "/react-app/build/:splat"


#https://answers.netlify.com/t/redirects-using-create-react-app/89676
[[redirects]]
  force = false
  from = "/*"
  status = 200
  to = "/react-app/build/index.html"




